# -*- coding: utf-8 -*-
"""ConversorMoedas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kl90YMuuf7nTctuiqykqfYQ1iyuw6zLN
"""

#Conversor de moedas v2.0
from time import sleep
for c in range(1,4):
        print(f'Começando conversor em {c}')
        sleep(1)
print('Bem vindo ao conversor de moedas')
while True:
    print('-=-' *10)
    continuar = input('Digite Enter se quiser iniciar/continuar: e digite X para sair: ').upper()
    print('-=-' *10)
    if continuar == '':
        pass
        print('-=-' *10)
        moeda = str(input('''Em qual moeda você deseja converter:
        Dólar - Digite DOLAR
        Euro - Digite EURO
        ''')).upper()
        if moeda == 'DOLAR':
            print('-=-' *10)
            valor = float(input('Qual o valor em R$ :'))
            print('-=-' *10)
            conversao = valor * 0.19
            print('-=-' *10)
            print(f'O valor {valor}, convertido em dolar é {conversao:.2f}')
            print('-=-' *10)
        elif moeda == 'EURO':
            print('-=-' *10)
            valor = float(input('Qual o valor em R$ :'))
            print('-=-' *10)
            conversao = valor * 0.18
            print('-=-' *10)
            print(f'O valor {valor}, convertido em euro é {conversao:.2f}')
            print('-=-' *10)
        else:
            break
    else:
        break